apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordermanager
  labels:
    app: ordermanager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordermanager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ordermanager
    spec:
      containers:
      - image: 566034038752.dkr.ecr.us-west-2.amazonaws.com/sykang/ordermanager:latest
        imagePullPolicy: Always
        name: ordermanager